/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarysearch;

public class App {

    public static void main(String[] args) {
        int[] binary = {2, 4, 6, 8};
        int target = 0;
        System.out.println(binarySearch(binary, target));
    }

    public static int binarySearch(int[] arr, int value) {
        int low = 0;
        int high = arr.length - 1;
        while (low <= high) {
            int mid = (low + high) / 2;
            if (arr[mid] == value)
                return mid;
            else if (arr[mid] < value) {
                low = mid + 1;
            } else {
                high = mid - 1;
            }
        }
        return -1;
    }
}
