/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void treeIntersection() {
        App app = new App();

        BinarySearchTree firstBinaryTree =new BinarySearchTree();
        firstBinaryTree.root=new Node(8);
        firstBinaryTree.Add(3);
        firstBinaryTree.Add(10);
        firstBinaryTree.Add(1);
        firstBinaryTree.Add(6);
        firstBinaryTree.Add(14);
        firstBinaryTree.Add(4);
        firstBinaryTree.Add(7);
        firstBinaryTree.Add(13);


        BinarySearchTree secondBinaryTree =new BinarySearchTree();
        secondBinaryTree.root=new Node(20);
        secondBinaryTree.Add(5);
        secondBinaryTree.Add(300);
        secondBinaryTree.Add(50);
        secondBinaryTree.Add(115);
        secondBinaryTree.Add(10);
        secondBinaryTree.Add(14);

        assertEquals(List.of(10,14), App.treeIntersection(firstBinaryTree,secondBinaryTree));
    }
}
