/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Class26;

import org.junit.Test;
import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void insertionTest(){
        int[] ReverseSorted ={20,18,12,8,5,-2};
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(App.InsertionSort(ReverseSorted)));
    }
    @Test
    public void insertionTest1(){
        int[] ReverseSorted ={5, 12, 7, 5, 5, 7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(App.InsertionSort(ReverseSorted)));
    }
    @Test
    public void insertionTest2(){
        int[] ReverseSorted ={2, 3, 5, 7, 13, 11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.InsertionSort(ReverseSorted)));
    }
}
