/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        Graph graph = new Graph();
        Vertex vertex = new Vertex(1);
        Vertex outputAdd = graph.addNode(vertex);
        System.out.println(outputAdd);


        //
        BreadthFirst graphs = new BreadthFirst();
        Vertex Pandora = new Vertex("Pandora");
        graphs.addNode(Pandora);
        Vertex Arendelle = new Vertex("Arendelle");
        graphs.addNode(Arendelle);
        Vertex Metroville = new Vertex("Metroville");
        graphs.addNode(Metroville);
        Vertex Monstroplolis = new Vertex("Monstroplolis");
        graphs.addNode(Monstroplolis);
        Vertex Narnia = new Vertex("Narnia");
        graphs.addNode(Narnia);
        Vertex Naboo = new Vertex("Naboo");
        graphs.addNode(Naboo);

        graphs.addEdge(Pandora,Arendelle,0);
        graphs.addEdge(Arendelle,Metroville,0);
        graphs.addEdge(Arendelle,Monstroplolis,0);
        graphs.addEdge(Metroville,Monstroplolis,0);
        graphs.addEdge(Metroville,Narnia,0);
        graphs.addEdge(Metroville,Naboo,0);
        graphs.addEdge(Monstroplolis,Naboo,0);
        graphs.addEdge(Narnia,Naboo,0);
        System.out.println(graphs.breadthFirstMethod(Pandora));

        //

        GetEdge getEdge = new GetEdge();
        getEdge.addNode(Pandora);
        getEdge.addNode(Arendelle);
        getEdge.addNode(Metroville);
        getEdge.addNode(Monstroplolis);
        getEdge.addNode(Narnia);
        getEdge.addNode(Naboo);

        getEdge.addEdge(Pandora,Arendelle,150);
        getEdge.addEdge(Pandora,Metroville,82);
        getEdge.addEdge(Arendelle,Metroville,99);
        ArrayList trip = new ArrayList();
        trip.add("Metroville");
        trip.add("Pandora");
        trip.add("Arendelle");

        System.out.println(GetEdge.checkFullTripPossibility(getEdge,trip));
    }
}
