/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.insert.shift;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ArrayShiftTest {
    @Test void someLibraryMethodReturnsTrue() {
        ArrayShift classUnderTest = new ArrayShift();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test public void arrayShift(){
        ArrayShift arrayShift = new ArrayShift();

        //test shift inset array
        int[] evenArray={20,40,80,100};
        int[] oddArray={20,40,80,120,140};
        int[] emptyArray={};
        assertEquals(60,ArrayShift.insertShiftArray(evenArray,60)[evenArray.length/2]);
        assertEquals(100,ArrayShift.insertShiftArray(oddArray,100)[(oddArray.length+1)/2]);
        assertEquals(0,ArrayShift.insertShiftArray(emptyArray,0)[0]);

    }
}
