/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testInsertionMethod(){
        LinkedList linkedList = new LinkedList();
        assertEquals(null,linkedList.head,"Test The initial value of the head of linked list without insert value");

        linkedList.insert(1);
        assertEquals(1,linkedList.head.value,"Test The initial value of the head of linked list after insert value");

        linkedList.insert(2);
        assertEquals(2,linkedList.head.value,"Test The initial value of the head of linked list after add 2 value");
    }
    @Test public void testIncludeMethod() {
        LinkedList linkedList = new LinkedList();
        linkedList.insert(1);
        linkedList.insert(2);

        assertTrue(linkedList.include(2));
        assertFalse(linkedList.include(5));
    }
    @Test public void testToString() {
        LinkedList linkedList = new LinkedList();
        assertEquals("Null",linkedList.toString());

        linkedList.insert(1);
        linkedList.insert(2);
        linkedList.insert(0);

        assertEquals("{ 0 } -> { 2 } -> { 1 } -> Null",linkedList.toString());
    }
}
