/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarysearch;

import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void oddBinarySearch(){
        App app = new App();
        int[] array ={1,2,3,4,5,6,7};
        int target = 6;
        assertEquals(5,App.binarySearch(array,target));
    }
    @Test
    public void evenBinarySearch(){
        App app = new App();
        int[] array ={1,2,3,4,5,6};
        int target = 5;
        assertEquals(4,App.binarySearch(array,target));
    }
    @Test
    public void notFoundBinarySearch(){
        App app = new App();
        int[] array ={1,2,3,4,5,6,7};
        int target = 9;
        assertEquals(-1,App.binarySearch(array,target));
    }
    @Test
    public void emptyArrayBinarySearch(){
        App app = new App();
        int[] array ={};
        int target = 5;
        assertEquals(-1,App.binarySearch(array,target));
    }
}
