/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class App {

    public static void main(String[] args) {
        BinarySearchTree binarySearchTree =new BinarySearchTree();
        binarySearchTree.Add(50);
        binarySearchTree.Add(30);
        binarySearchTree.Add(20);
        binarySearchTree.Add(40);
        binarySearchTree.Add(70);
        binarySearchTree.Add(60);
        binarySearchTree.Add(80);
        System.out.println(binarySearchTree.postOrder(binarySearchTree.root));
        System.out.println(binarySearchTree.contains(90));
        System.out.println(binarySearchTree.contains(80));
    }
}
