/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {

    public static <T> void main(String[] args) {
        Stack<Integer> stack=new Stack<>();
//        stack.push(5);
//        stack.push(4);
//        stack.push(3);
        T value = stack.pop();
        T peekValue = stack.peek();
        System.out.println(value);
//        System.out.println(peekValue);
//        System.out.println(stack.toString());

        //add queue method
        Queue<Integer> queue =new Queue<>();
        queue.enqueue(8);
        queue.enqueue(5);
        queue.enqueue(53);
        T valueOfDeQueue=queue.deQueue();
        System.out.println(valueOfDeQueue);
        System.out.println(queue.toString());

        //
        PseudoQueue pseudoQueue =new PseudoQueue();
        pseudoQueue.enqueue(3);
        pseudoQueue.enqueue(4);
        pseudoQueue.enqueue(5);
        T pseValue= (T) pseudoQueue.dequeue();
        System.out.println(pseValue);
        System.out.println(pseudoQueue.toString());
    }
}
