/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.insert.shift;

import java.util.Arrays;

public class ArrayShift {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        int[] evenInsetArray={1,2,4,5};
        int[] oddInsetArray={1,2,31,5,6};

        System.out.println(Arrays.toString(insertShiftArray(evenInsetArray,3)));
        System.out.println(Arrays.toString(insertShiftArray(oddInsetArray,32)));
    }
    public static int[] insertShiftArray(int[] arr,int value) {
        int[] newArray = new int[arr.length + 1];
        int index = arr.length % 2 == 0 ? arr.length / 2 : (arr.length + 1) / 2;
        newArray[index] = value;
        for (int i = 0; i < arr.length; i++) {
            if (i >= index) {
                newArray[i + 1] = arr[i];
            } else {
                newArray[i] = arr[i];
            }
        }
        return newArray;
    }
}
