/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {


    public static void main(String[] args) {
        HashTable<Integer,String> hashTable = new HashTable<>();

        System.out.println(hashTable.getSize());
        System.out.println(hashTable.isEmpty());

        hashTable.add(7,"Ali");
        hashTable.add(5,"Ahmad");
        hashTable.add(3,"Emam");

        System.out.println(hashTable.isEmpty());

        System.out.println(hashTable.getSize());

        System.out.println(hashTable.get(5));

        System.out.println(hashTable.contains(7));
        System.out.println(hashTable.contains(9));
    }
}
