/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {

    public static void main(String[] args) {
        LinkedList<Integer> linkedList =new LinkedList<>();
        linkedList.insert(5);
        linkedList.insert(4);
        linkedList.insert(3);
        linkedList.insert(2);
        linkedList.insert(1);
        linkedList.insert(0);
        linkedList.append(6);
        linkedList.append(7);
        linkedList.append(8);
        linkedList.insertBefore(0,29);
        linkedList.insertAfter(5,55);
        linkedList.deleteNodeByKey(55);
        linkedList.deleteNodeByKey(0);
        System.out.println(linkedList.include(5));
        System.out.println(linkedList.toString());

    }
}
