/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {

    public static void main(String[] args) {
        LinkedList<Integer> linkedList =new LinkedList<>();
        linkedList.insert(5);
        linkedList.insert(4);
        linkedList.insert(3);
        System.out.println(linkedList.toString());
    }
}
